import uuid
from decimal import Decimal
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field


class SourceEvidence(BaseModel):
    """
    Authoritative source citation generated by deterministic parser or OCR engine.
    The LLM never generates this directly; it only references the evidence_id.
    """

    evidence_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    type: Literal["spreadsheet", "pdf", "ocr_pdf"]
    sheet: str | None = None
    row: int | None = None
    cells: list[str] = Field(default_factory=list)
    page: int | None = None
    bbox: list[float] | None = None  # [x0, y0, x1, y1]
    text_snippet: str | None = None
    ocr_confidence: float | None = None

    @property
    def row_idx(self) -> int | None:
        return self.row

    @property
    def sheet_name(self) -> str | None:
        return self.sheet

    def to_dict(self) -> dict[str, Any]:
        d = self.model_dump(exclude_none=True)
        if self.row is not None:
            d["row_idx"] = self.row
        if self.sheet is not None:
            d["sheet_name"] = self.sheet
        return d


class RawLineItem(BaseModel):
    description_raw: str
    quantity: Decimal
    unit: str = "units"
    unit_price: Decimal
    currency: str = "USD"
    total_price: Decimal
    lead_time_days: int | None = None
    confidence: Decimal = Decimal("1.0")
    evidence: SourceEvidence
    warnings: list[str] = Field(default_factory=list)
    rfq_line_item_id: str | None = None
    match_confidence: Decimal | None = None


class RawQuotationField(BaseModel):
    field_name: str
    raw_value: str | None = None
    normalised_value: dict[str, Any] | None = None
    confidence: Decimal = Decimal("1.0")
    evidence: SourceEvidence
    warnings: list[str] = Field(default_factory=list)


class ExtractedQuotationData(BaseModel):
    extraction_model: str
    extraction_version: str = "1.0"
    overall_confidence: Decimal = Decimal("1.0")
    supplier_name: str | None = None
    supplier_reference: str | None = None
    line_items: list[RawLineItem] = Field(default_factory=list)
    fields: list[RawQuotationField] = Field(default_factory=list)
    notes: str | None = None
    raw_llm_output: dict[str, Any] | None = None
    validation_warnings: list[str] = Field(default_factory=list)


class BaseExtractor:
    """Abstract base extractor interface."""

    def extract(self, file_path: Path, **kwargs: Any) -> ExtractedQuotationData:
        raise NotImplementedError
