"""phase6_decision_tables

Revision ID: 2231598cc1bc
Revises: 
Create Date: 2026-09-15 22:34:13.949913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '2231598cc1bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfq_fx_rate_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rfq_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('provider_id', sa.String(length=100), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('rates', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fx_rateset_rfq_ver', 'rfq_fx_rate_sets', ['rfq_id', 'version'], unique=True)
    op.create_table('scoring_configurations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rfq_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_configurations_rfq_id'), 'scoring_configurations', ['rfq_id'], unique=False)
    op.create_table('comparison_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rfq_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('normalization_engine_version', sa.String(length=50), nullable=False),
    sa.Column('reference_currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate_set_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('matrix_data', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fx_rate_set_id'], ['rfq_fx_rate_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comparison_snapshot_rfq_ver', 'comparison_snapshots', ['rfq_id', 'snapshot_version'], unique=True)
    op.create_table('scoring_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rfq_id', sa.String(length=36), nullable=False),
    sa.Column('configuration_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('results_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('provenance_hash', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['scoring_configurations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['comparison_snapshots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_runs_configuration_id'), 'scoring_runs', ['configuration_id'], unique=False)
    op.create_index(op.f('ix_scoring_runs_rfq_id'), 'scoring_runs', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_scoring_runs_snapshot_id'), 'scoring_runs', ['snapshot_id'], unique=False)
    op.create_table('decision_contexts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rfq_id', sa.String(length=36), nullable=False),
    sa.Column('scoring_run_id', sa.String(length=36), nullable=False),
    sa.Column('context_schema_version', sa.String(length=50), nullable=False),
    sa.Column('context_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('provider_projection', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('includes_sensitivity', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scoring_run_id'], ['scoring_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_contexts_rfq_id'), 'decision_contexts', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_decision_contexts_scoring_run_id'), 'decision_contexts', ['scoring_run_id'], unique=False)
    op.create_table('normalization_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rfq_id', sa.String(length=36), nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('line_item_id', sa.String(length=36), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('original_value', sa.JSON(), nullable=False),
    sa.Column('previous_normalized_value', sa.JSON(), nullable=True),
    sa.Column('override_value', sa.JSON(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reverted_by', sa.String(length=100), nullable=True),
    sa.Column('revert_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['line_item_id'], ['extracted_line_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['supplier_quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_norm_override_rfq', 'normalization_overrides', ['rfq_id', 'is_active'], unique=False)
    op.create_table('narrative_generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rfq_id', sa.String(length=36), nullable=False),
    sa.Column('decision_context_id', sa.String(length=36), nullable=False),
    sa.Column('narrative_type', sa.Enum('COMPARISON_SUMMARY', 'TRADEOFF_ANALYSIS', 'SENSITIVITY_SUMMARY', 'DECISION_SUPPORT_MEMO', 'DECISION_CONSIDERATIONS', name='narrativetype'), nullable=False),
    sa.Column('generation_number', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Enum('AI_GENERATED', 'AI_GENERATED_HUMAN_REVISED', 'HUMAN_AUTHORED', name='narrativeorigin'), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model_identifier', sa.String(length=200), nullable=False),
    sa.Column('prompt_template_version', sa.String(length=50), nullable=False),
    sa.Column('prompt_template_hash', sa.String(length=64), nullable=False),
    sa.Column('rendered_prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('response_schema_version', sa.String(length=50), nullable=False),
    sa.Column('generation_parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('raw_structured_output', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=False),
    sa.Column('grounding_validation_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_superseded', sa.Boolean(), nullable=False),
    sa.Column('superseded_reason', sa.String(length=500), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['decision_context_id'], ['decision_contexts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrative_generations_decision_context_id'), 'narrative_generations', ['decision_context_id'], unique=False)
    op.create_index(op.f('ix_narrative_generations_rfq_id'), 'narrative_generations', ['rfq_id'], unique=False)
    op.create_table('award_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rfq_id', sa.String(length=36), nullable=False),
    sa.Column('scoring_run_id', sa.String(length=36), nullable=False),
    sa.Column('narrative_generation_id', sa.String(length=36), nullable=True),
    sa.Column('awarded_supplier_id', sa.String(length=36), nullable=False),
    sa.Column('awarded_supplier_name', sa.String(length=255), nullable=False),
    sa.Column('awarded_supplier_rank', sa.Integer(), nullable=True),
    sa.Column('non_rank1_rationale', sa.Text(), nullable=True),
    sa.Column('current_status', sa.Enum('DRAFT', 'CONFIRMED', 'REVOKED', name='awardstatus'), nullable=False),
    sa.Column('provenance_hash', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['narrative_generation_id'], ['narrative_generations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scoring_run_id'], ['scoring_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_award_rfq_status', 'award_decisions', ['rfq_id', 'current_status'], unique=False)
    op.create_index('uq_award_rfq_confirmed', 'award_decisions', ['rfq_id'], unique=True, postgresql_where=sa.text("current_status = 'CONFIRMED'"), sqlite_where=sa.text("current_status = 'CONFIRMED'"))
    op.create_index(op.f('ix_award_decisions_rfq_id'), 'award_decisions', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_award_decisions_scoring_run_id'), 'award_decisions', ['scoring_run_id'], unique=False)
    op.create_table('narrative_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('narrative_generation_id', sa.String(length=36), nullable=False),
    sa.Column('claim_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.Enum('DETERMINISTIC_FACT', 'INTERPRETATION', 'LIMITATION', name='claimtype'), nullable=False),
    sa.Column('grounding_status', sa.Enum('VERIFIED', 'UNSUPPORTED', 'UNVERIFIABLE', name='groundingstatus'), nullable=False),
    sa.Column('referenced_supplier_ids', sa.JSON(), nullable=False),
    sa.Column('referenced_criterion_ids', sa.JSON(), nullable=False),
    sa.Column('referenced_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('fact_references', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('grounding_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['narrative_generation_id'], ['narrative_generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrative_claims_narrative_generation_id'), 'narrative_claims', ['narrative_generation_id'], unique=False)
    op.create_table('narrative_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('narrative_generation_id', sa.String(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('revised_text', sa.Text(), nullable=False),
    sa.Column('revision_rationale', sa.Text(), nullable=True),
    sa.Column('revised_by', sa.String(length=100), nullable=False),
    sa.Column('revised_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['narrative_generation_id'], ['narrative_generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrative_revisions_narrative_generation_id'), 'narrative_revisions', ['narrative_generation_id'], unique=False)
    op.create_table('award_decision_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('award_decision_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('DRAFT_CREATED', 'CONFIRMED', 'REVOKED', name='awardeventtype'), nullable=False),
    sa.Column('event_number', sa.Integer(), nullable=False),
    sa.Column('event_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('actor_principal', sa.String(length=100), nullable=False),
    sa.Column('actor_display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['award_decision_id'], ['award_decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_award_decision_events_award_decision_id'), 'award_decision_events', ['award_decision_id'], unique=False)
    op.drop_table('procurement_decisions')
    op.drop_table('supplier_scores')
    op.drop_table('criterion_scores')
    op.drop_table('ai_narratives')
    op.drop_table('score_results')
    op.add_column('extracted_line_items', sa.Column('calculated_total_price', sa.Numeric(precision=14, scale=4), nullable=True))
    op.add_column('extracted_line_items', sa.Column('source_evidence', sa.JSON(), nullable=True))
    op.add_column('extracted_line_items', sa.Column('is_removed', sa.Boolean(), nullable=False))
    op.add_column('extracted_line_items', sa.Column('removal_reason', sa.String(length=255), nullable=True))
    op.add_column('extracted_quotation_fields', sa.Column('source_evidence', sa.JSON(), nullable=True))
    op.add_column('extracted_quotations', sa.Column('is_current', sa.Boolean(), nullable=False))
    op.add_column('extracted_quotations', sa.Column('acknowledged_warnings', sa.JSON(), nullable=True))
    op.create_index('uq_current_extraction_per_quotation', 'extracted_quotations', ['quotation_id'], unique=True, postgresql_where=sa.text('is_current = true'), sqlite_where=sa.text('is_current = 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_current_extraction_per_quotation', table_name='extracted_quotations', postgresql_where=sa.text('is_current = true'), sqlite_where=sa.text('is_current = 1'))
    op.drop_column('extracted_quotations', 'acknowledged_warnings')
    op.drop_column('extracted_quotations', 'is_current')
    op.drop_column('extracted_quotation_fields', 'source_evidence')
    op.drop_column('extracted_line_items', 'removal_reason')
    op.drop_column('extracted_line_items', 'is_removed')
    op.drop_column('extracted_line_items', 'source_evidence')
    op.drop_column('extracted_line_items', 'calculated_total_price')
    op.create_table('score_results',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('rfq_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('scoring_strategy', sa.VARCHAR(length=100), nullable=False),
    sa.Column('computed_at', sa.DATETIME(), nullable=False),
    sa.Column('currency_snapshot', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_narratives',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('score_result_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('model_used', sa.VARCHAR(length=100), nullable=False),
    sa.Column('prompt_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('raw_text', sa.TEXT(), nullable=False),
    sa.Column('edited_text', sa.TEXT(), nullable=True),
    sa.Column('generated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['score_result_id'], ['score_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criterion_scores',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('supplier_score_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('criterion_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('criterion_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('raw_value', sa.VARCHAR(length=100), nullable=True),
    sa.Column('normalised_value', sa.NUMERIC(precision=7, scale=4), nullable=False),
    sa.Column('weighted_contribution', sa.NUMERIC(precision=7, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['evaluation_criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_score_id'], ['supplier_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_scores',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('score_result_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('quotation_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('supplier_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('total_score', sa.NUMERIC(precision=7, scale=4), nullable=False),
    sa.Column('rank', sa.INTEGER(), nullable=False),
    sa.Column('is_eliminated', sa.BOOLEAN(), nullable=False),
    sa.Column('elimination_reason', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['supplier_quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['score_result_id'], ['score_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procurement_decisions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('rfq_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('score_result_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('decided_at', sa.DATETIME(), nullable=False),
    sa.Column('decided_by', sa.VARCHAR(length=100), nullable=False),
    sa.Column('selected_quotation_ids', sqlite.JSON(), nullable=False),
    sa.Column('justification', sa.TEXT(), nullable=False),
    sa.Column('followed_ai_recommendation', sa.BOOLEAN(), nullable=False),
    sa.Column('is_partial_award', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['score_result_id'], ['score_results.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_award_decision_events_award_decision_id'), table_name='award_decision_events')
    op.drop_table('award_decision_events')
    op.drop_index(op.f('ix_narrative_revisions_narrative_generation_id'), table_name='narrative_revisions')
    op.drop_table('narrative_revisions')
    op.drop_index(op.f('ix_narrative_claims_narrative_generation_id'), table_name='narrative_claims')
    op.drop_table('narrative_claims')
    op.drop_index(op.f('ix_award_decisions_scoring_run_id'), table_name='award_decisions')
    op.drop_index(op.f('ix_award_decisions_rfq_id'), table_name='award_decisions')
    op.drop_index('uq_award_rfq_confirmed', table_name='award_decisions', postgresql_where=sa.text("current_status = 'CONFIRMED'"), sqlite_where=sa.text("current_status = 'CONFIRMED'"))
    op.drop_index('idx_award_rfq_status', table_name='award_decisions')
    op.drop_table('award_decisions')
    op.drop_index(op.f('ix_narrative_generations_rfq_id'), table_name='narrative_generations')
    op.drop_index(op.f('ix_narrative_generations_decision_context_id'), table_name='narrative_generations')
    op.drop_table('narrative_generations')
    op.drop_index('idx_norm_override_rfq', table_name='normalization_overrides')
    op.drop_table('normalization_overrides')
    op.drop_index(op.f('ix_decision_contexts_scoring_run_id'), table_name='decision_contexts')
    op.drop_index(op.f('ix_decision_contexts_rfq_id'), table_name='decision_contexts')
    op.drop_table('decision_contexts')
    op.drop_index(op.f('ix_scoring_runs_snapshot_id'), table_name='scoring_runs')
    op.drop_index(op.f('ix_scoring_runs_rfq_id'), table_name='scoring_runs')
    op.drop_index(op.f('ix_scoring_runs_configuration_id'), table_name='scoring_runs')
    op.drop_table('scoring_runs')
    op.drop_index('idx_comparison_snapshot_rfq_ver', table_name='comparison_snapshots')
    op.drop_table('comparison_snapshots')
    op.drop_index(op.f('ix_scoring_configurations_rfq_id'), table_name='scoring_configurations')
    op.drop_table('scoring_configurations')
    op.drop_index('idx_fx_rateset_rfq_ver', table_name='rfq_fx_rate_sets')
    op.drop_table('rfq_fx_rate_sets')
    # ### end Alembic commands ###
